name: Build Frontend Assets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: npm install
      - run: npm run prod
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt -y update
            sudo apt install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            cd /home
            ls
            cd ubuntu
            sudo yum install nodejs npm -y
            npm install
            sudo npm run build
            cd build
            sudo mv * /var/www/html/NexoPOS
            sudo systemctl restart httpd
